Add failure test case
ftdebugger/di.js pull request #17
Opened 2016-09-14 16:35 UTC by jakwuh

2016-09-14 16:38 UTC, jakwuh commented
This test case should pass but it fails. Let me give some explanations.
When we use following definition:
```js
A: {
    test: 'Test'
},

A1: '!A#a',
A2: '!A#b'
```
then we expect  A1 and A2 still be reuse one instance A, but call different update method on it. In fact, as far as `A#a` and `A#b` are different moduleId's in `di.js`, we result into different instances.

I think this should be fixed.

2016-09-14 16:40 UTC, jakwuh commented
@ftdebugger if you see the problem and agree with it, let me know so I will try to fix it.

2016-09-16 07:55 UTC, ftdebugger commented
👍

2016-09-16 21:16 UTC, jakwuh commented
@ftdebugger please take a short look cause I need this pr to be merged & published

2016-09-20 09:15 UTC, ftdebugger requested changes
Check my notes

2016-09-20 09:15 UTC, ftdebugger commented on index.js
> +        let {bundleName, factory, update} = parseStringDefinition(definition.slice(1));
Definition already parsed:

``` js
let bundleName: matches[1],
    factory: matches[3],
    update: matches[5];
```

2016-09-20 09:15 UTC, ftdebugger commented on index.js
> +            reuse = `${bundleName}.${factory}`;
Looks like inconsistent here, you can override update method, but not factory. How about allow define factory for each reuse too? It is make sense, when you need different construct strategy for each reuse at first use.

I think `bundleName` is enough.

``` js
    let matches = definition ?
        definition.match(/^!?([^.#]+)(\.([^#]+))?(#(.+))?$/) :
        null;

    if (!matches) {
        throw new Error('Unknown module format: ' + JSON.stringify(definition));
    }

    let bundleName = matches[1],
        factory = matches[3],
        update = matches[5];

    if (definition[0] === '!') {
        let reuseDefinition = {
            reuse: bundleName
        };

        if (factory) {
            reuseDefinition.factory = factory;
        }

        if (update) {
            reuseDefinition.update = update;
        }

        return reuseDefinition;
    } else {
        return {
            parentId: definition,
            bundleName,
            factory,
            update
        };
    }
```

2016-09-20 15:00 UTC, ftdebugger approved these changes

2016-09-20 15:00 UTC, merged